version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/blog_cn"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm"
    directory: "/blog_en"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    open-pull-requests-limit: 10
